### ISSUE TITLE
DooFree when installed automatically is disabled not sure why exactly

### ISSUE THREAD

**Issue by ohmichael** [mpie/doofree#1]
I have to enable it after install and even then when when I try to open it it gives me an error and it says version 5.0.2 when your addon sheet says 5.0.3. Just letting you know so you can fix it thx for all you do.

**Comment by mpie** [comment]
@ohmichael I've managed to do some rework on the addon. It should work now. 
Can you give it a try?

**Comment by ohmichael** [comment]
Worked thx

**Comment by mpie** [comment]
Awesome.
